version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend_static:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.local
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/media/:ro
    networks:
      - frontend
    depends_on:
      - web

networks:
  frontend:
  backend:

volumes:
  db:
  backend_static:
  media_value: 