# Generated by Django 3.2.20 on 2025-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Input measurement units', max_length=50, verbose_name='Measurement units'),
        ),
    ]
